# centos docker installation
- name: create docker api config directory
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy tcp ip setting
  copy:
    src: ../tcp_api_settings.txt
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: install docker dependencies
  yum: 
    name={{item}}
    state=present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2  

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo  

- name: install docker-ce
  yum:
    name: docker-ce  

- name: restart docker daemon
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl restart docker       