# ubuntu docker installation
- name: create docker api config directory
  file: 
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: copy tcp ip setting
  copy:
    src: ../tcp_api_settings.txt
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: 'install docker dependencies'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'apt-transport-https'
    - 'curl'
    - 'python-pip'

- name: install docker py
  pip:
    name: docker

- name: 'add docker repo apt key'
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: 'add Docker repository'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: 'present'

- name: 'install docker-ce'
  apt:
    name: docker-ce

- name: restart docker daemon
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl restart docker.service